version: '3.8'

services:
  playwright-mcp-1:
    build: .
    container_name: Playwright-MCP-1
    ports:
      - "127.0.0.1:8081:8080"
    environment:
      - NODE_ENV=production
      - DISPLAY=:99
      - PLAYWRIGHT_BROWSERS_PATH=/home/playwright/.cache/ms-playwright
      - PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=0
      - PLAYWRIGHT_ISOLATED_BROWSER=1
      - CHROME_NO_SANDBOX=1
      - CHROME_DISABLE_GPU=1
      - CHROME_DISABLE_DEV_SHM=1
    volumes:
      - screenshots:/app/screenshots
      - downloads:/app/downloads
      - output:/app/output
      - browser_cache:/home/playwright/.cache/ms-playwright
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/app/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  playwright-mcp-2:
    build: .
    container_name: Playwright-MCP-2
    ports:
      - "127.0.0.1:8082:8080"
    environment:
      - NODE_ENV=production
      - DISPLAY=:99
      - PLAYWRIGHT_BROWSERS_PATH=/home/playwright/.cache/ms-playwright
      - PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=0
      - PLAYWRIGHT_ISOLATED_BROWSER=1
      - CHROME_NO_SANDBOX=1
      - CHROME_DISABLE_GPU=1
      - CHROME_DISABLE_DEV_SHM=1
    volumes:
      - screenshots:/app/screenshots
      - downloads:/app/downloads
      - output:/app/output
      - browser_cache:/home/playwright/.cache/ms-playwright
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/app/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  playwright-mcp-3:
    build: .
    container_name: Playwright-MCP-3
    ports:
      - "127.0.0.1:8083:8080"
    environment:
      - NODE_ENV=production
      - DISPLAY=:99
      - PLAYWRIGHT_BROWSERS_PATH=/home/playwright/.cache/ms-playwright
      - PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=0
      - PLAYWRIGHT_ISOLATED_BROWSER=1
      - CHROME_NO_SANDBOX=1
      - CHROME_DISABLE_GPU=1
      - CHROME_DISABLE_DEV_SHM=1
    volumes:
      - screenshots:/app/screenshots
      - downloads:/app/downloads
      - output:/app/output
      - browser_cache:/home/playwright/.cache/ms-playwright
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/app/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  playwright-mcp-4:
    build: .
    container_name: Playwright-MCP-4
    ports:
      - "127.0.0.1:8084:8080"
    environment:
      - NODE_ENV=production
      - DISPLAY=:99
      - PLAYWRIGHT_BROWSERS_PATH=/home/playwright/.cache/ms-playwright
      - PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=0
      - PLAYWRIGHT_ISOLATED_BROWSER=1
      - CHROME_NO_SANDBOX=1
      - CHROME_DISABLE_GPU=1
      - CHROME_DISABLE_DEV_SHM=1
    volumes:
      - screenshots:/app/screenshots
      - downloads:/app/downloads
      - output:/app/output
      - browser_cache:/home/playwright/.cache/ms-playwright
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/app/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  playwright-mcp-5:
    build: .
    container_name: Playwright-MCP-5
    ports:
      - "127.0.0.1:8085:8080"
    environment:
      - NODE_ENV=production
      - DISPLAY=:99
      - PLAYWRIGHT_BROWSERS_PATH=/home/playwright/.cache/ms-playwright
      - PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=0
      - PLAYWRIGHT_ISOLATED_BROWSER=1
      - CHROME_NO_SANDBOX=1
      - CHROME_DISABLE_GPU=1
      - CHROME_DISABLE_DEV_SHM=1
    volumes:
      - screenshots:/app/screenshots
      - downloads:/app/downloads
      - output:/app/output
      - browser_cache:/home/playwright/.cache/ms-playwright
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/app/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  screenshots:
  downloads:
  output:
  browser_cache:
