

services:
  playwright-mcp:
    build: .
    container_name: Playwright-MCP
    ports:
      - "127.0.0.1:8081:8080"  # Primary instance
      - "127.0.0.1:8082:8081"  # Secondary instance
      - "127.0.0.1:8083:8082"  # Tertiary instance
      - "127.0.0.1:8084:8083"  # Quaternary instance
      - "127.0.0.1:8085:8084"  # Quinary instance
    environment:
      - NODE_ENV=production
      - DISPLAY=:99
      - PLAYWRIGHT_BROWSERS_PATH=/home/playwright/.cache/ms-playwright
      - PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=0
      - PLAYWRIGHT_ISOLATED_BROWSER=1
      - CHROME_NO_SANDBOX=1
      - CHROME_DISABLE_GPU=1
      - CHROME_DISABLE_DEV_SHM=1
    volumes:
      - screenshots:/app/screenshots
      - downloads:/app/downloads
      - output:/app/output
      - browser_cache:/home/playwright/.cache/ms-playwright
      - logs:/app/logs
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_ADMIN
    healthcheck:
      test: ["CMD", "/app/healthcheck.sh"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 60s
    networks:
      Network-Bridge:
    # Add resource limits to prevent memory issues
    mem_limit: 6g
    mem_reservation: 3g
    # Add logging configuration with better rotation
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
        labels: "service=playwright-mcp"
        env: "NODE_ENV"
      
networks:
    Network-Bridge:
        external: true

volumes:
  screenshots:
  downloads:
  output:
  browser_cache:
  logs:
