version: '3.8'

services:
  playwright-mcp:
    build: .
    container_name: playwright-mcp-server
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - DISPLAY=:99
    volumes:
      - screenshots:/app/screenshots
      - downloads:/app/downloads
      - output:/app/output
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - playwright-network

networks:
  playwright-network:
    driver: bridge

volumes:
  screenshots:
  downloads:
  output:
