

services:
  playwright-mcp:
    build: .
    container_name: Playwright-MCP
    ports:
      - "127.0.0.1:8081:8080"
    environment:
      - NODE_ENV=production
      - DISPLAY=:99
    volumes:
      - screenshots:/app/screenshots
      - downloads:/app/downloads
      - output:/app/output
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pgrep", "-f", "mcp-server-playwright"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      Network-Bridge:
      
networks:
    Network-Bridge:
        external: true

volumes:
  screenshots:
  downloads:
  output:
